//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Friendship()
        {
            this.Friendship_message = new HashSet<Friendship_message>();
        }
    
        public int friendship_id { get; set; }
        public int user1_id { get; set; }
        public int user2_id { get; set; }
        public System.DateTime started { get; set; }
        public Nullable<System.DateTime> ended { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship_message> Friendship_message { get; set; }
    }
}
