//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chatdbEntities : DbContext
    {
        public chatdbEntities()
            : base("name=chatdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Friendship> Friendship { get; set; }
        public virtual DbSet<Chatroom_message> Chatroom_message { get; set; }
        public virtual DbSet<Friendship_message> Friendship_message { get; set; }
        public virtual DbSet<User_group> User_group { get; set; }
        public virtual DbSet<User_group_right> User_group_right { get; set; }
    }
}
