//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatRoom.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_group
    {
        public int user_group_id { get; set; }
        public Nullable<int> user_group_right_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
    
        public virtual User User { get; set; }
        public virtual User_group_right User_group_right { get; set; }
    }
}
